### ISSUE TITLE
Link to/from Areweyet

### ISSUE THREAD

**Issue by crsaracco** [RustAudio/areweaudioyet#10]
Some people on /r/rust [mentioned](https://old.reddit.com/r/rust/comments/cqyvbf/are_we_x_yet_why_are_these_sites_not_linked/) that it might be a good idea to link back to [Areweyet](https://wiki.mozilla.org/Areweyet), mozilla's meta-list of "Are we X yet" sites, for discoverability purposes.

While we're at it, we might as well put ourselves in that meta-list :)

**Comment by Walther** [comment]
Thanks for the idea! Added to the wiki: https://wiki.mozilla.org/Areweyet

**Comment by Walther** [comment]
oops, going to add the linkback too

**Comment by Walther** [comment]
Fixed with 0deba4f92a04d96001b99217154b8dfae569d529
