### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by madskjeldgaard** [RustAudio/areweaudioyet#11]
The link `https://areweaudioyet.com/` is dead

**Comment by Walther** [comment]
Thanks for reporting!
Sorry for the downtime, this is currently between hosting providers, I need to set this up again.
Luckily (and sadly) the site does not even have that much on it.

**Comment by marioortizmanero** [comment]
Sorry to bother. It's still down, did you have problems setting it up?

I found this site [here](https://wiki.mozilla.org/Areweyet), so in case you aren't going to work on this anymore please let me know to remove it from there.

**Comment by Windfisch** [comment]
I am currently writing a loop machine in Rust and just going down the rabbit hole of how to do realtime stuff The Right Way in Rust; If you need more content, I'd love to write down my findings, hoping they could help others too ;)

**Comment by Walther** [comment]
Sorry for the delay & for auto-closing the issue with a magic comment on a PR that didn't actually end up deploying.
Still working on this, just a moment!

**Comment by Walther** [comment]
Finally fixed, sorry for the delay 🙇 
https://areweaudioyet.com/

**Comment by madskjeldgaard** [comment]
Thanks !




On Sat, Jul 4, 2020 at 12:24 AM +0200, "Veeti Haapsamo" <notifications@github.com> wrote:















Closed #11.
